volumes:
    mysql-data:

services:

    mysql:
        container_name: mysql
        platform: linux/x86_64
        image: mysql:8.0.28
        restart: unless-stopped
        volumes:
            - mysql-data:/var/lib/mysql:rw
        ports:
            - "3306:3306"
        environment:
            MYSQL_ROOT_PASSWORD: password
            MYSQL_DATABASE: db

    php:
        container_name: tax-backend-v2
        build:
            context: ./backend
            dockerfile: ./src/Dockerfile
        #restart: always
        volumes:
            - ./backend/app:/app:rw

    backend:
        container_name: tax-backend-v2-nginx
        image: nginx:1.21.6-alpine
        #restart: always
        volumes:
            - ./backend/app:/app:rw
            - ./backend/src/nginx.conf:/etc/nginx/conf.d/default.conf:rw
        ports:
            - "80:81"
        depends_on:
            - php

